// <auto-generated />
using System;
using GardenHelperWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GardenHelperWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GardenHelperWebAPI.Models.EdibleLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AmountHarvested")
                        .HasColumnType("float");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DaysToHarvest")
                        .HasColumnType("int");

                    b.Property<bool>("Harvested")
                        .HasColumnType("bit");

                    b.Property<double>("PlantId")
                        .HasColumnType("float");

                    b.Property<int>("Quality")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EdibleLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountHarvested = 10.0,
                            Date = "",
                            DaysToHarvest = 2,
                            Harvested = true,
                            PlantId = 1.0,
                            Quality = 0
                        });
                });

            modelBuilder.Entity("GardenHelperWebAPI.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Light")
                        .HasColumnType("float");

                    b.Property<double>("PlantId")
                        .HasColumnType("float");

                    b.Property<bool>("PredictionAccurate")
                        .HasColumnType("bit");

                    b.Property<double>("SoilMoisture")
                        .HasColumnType("float");

                    b.Property<double>("SoilPH")
                        .HasColumnType("float");

                    b.Property<bool>("WaterPrediction")
                        .HasColumnType("bit");

                    b.Property<bool>("WateredToday")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Logs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "",
                            HealthStatus = "",
                            Height = 10.0,
                            ImageUrl = "https://bs.floristic.org/image/o/63073d2fbf45b90701279405ecc2eec0272906ed",
                            Light = 10.0,
                            PlantId = 1.0,
                            PredictionAccurate = true,
                            SoilMoisture = 0.0,
                            SoilPH = 7.0,
                            WaterPrediction = true,
                            WateredToday = true
                        });
                });

            modelBuilder.Entity("GardenHelperWebAPI.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AtmosphericHumidity")
                        .HasColumnType("int");

                    b.Property<string>("CommonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatePlanted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Edible")
                        .HasColumnType("bit");

                    b.Property<int>("GardenerId")
                        .HasColumnType("int");

                    b.Property<string>("HealthStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastWatering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Light")
                        .HasColumnType("float");

                    b.Property<double?>("MaxPH")
                        .HasColumnType("float");

                    b.Property<double?>("MaxPrecipitation")
                        .HasColumnType("float");

                    b.Property<double?>("MaxTemp")
                        .HasColumnType("float");

                    b.Property<double?>("MinPH")
                        .HasColumnType("float");

                    b.Property<double?>("MinPrecipitation")
                        .HasColumnType("float");

                    b.Property<double?>("MinTemp")
                        .HasColumnType("float");

                    b.Property<int?>("RequiredLight")
                        .HasColumnType("int");

                    b.Property<int?>("SoilHumidity")
                        .HasColumnType("int");

                    b.Property<double>("SoilMoisture")
                        .HasColumnType("float");

                    b.Property<double>("SoilPH")
                        .HasColumnType("float");

                    b.Property<double>("SpeciesId")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtmosphericHumidity = 5,
                            CommonName = "Spinach",
                            DatePlanted = "",
                            Edible = true,
                            GardenerId = 1,
                            HealthStatus = "Good",
                            Height = 10.0,
                            ImageUrl = "https://bs.plantnet.org/image/o/3cc08d812a893df9a574b1d377dc5b7c4d6477bc",
                            LastWatering = "",
                            Light = 7.0,
                            MaxPH = 7.5,
                            MinPH = 7.0,
                            RequiredLight = 7,
                            SoilMoisture = 0.0,
                            SoilPH = 7.0,
                            SpeciesId = 183722.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
